In [3]:
import os
import tarfile
import urllib

In [4]:
HOUSING_PATH="./datasets/housing/"

In [5]:
import pandas as pd

def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path,"housing.csv")
    return pd.read_csv(csv_path)

In [6]:
housing = load_housing_data()

In [7]:
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [8]:
import matplotlib.pyplot as plt

In [9]:
import numpy as np

In [10]:
def split_train_test(data,test_ratio):
    shuffled_indices = np.random.permutation(len(data))
    test_set_size = int(len(data)*test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [11]:
from zlib import crc32

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
housing["income_cat"]= pd.cut(housing["median_income"], bins=[0.,1.5,3.0,4.5,6.0,np.inf],labels=[1,2,3,4,5])

In [14]:
from sklearn.model_selection import StratifiedShuffleSplit

In [15]:
from pandas.plotting import scatter_matrix

In [16]:
from pylab import *

 ### 210121 기록
 
 # 2.5 머신러닝 알고리즘을 위한 데이터 준비

## 2.5.1 데이터 정제

대부분의 머신러닝 알고리즘은 누락된 특성을 다루지 못하므로 이를 처리할 수 있는 함수를 몇개 만들겠습니다. 앞서 total_bedrooms 특성에 값이 없는 경우를 보았는데 이를 고쳐보겠습니다. 방법은 3가지 입니다. 

- 해당 구역을 제거합니다

- 전체 특성을 삭제합니다.

- 어떤 값으로 채웁니다(0,평균,중간값등)

데이터프레임의 dropna(),drop(),fillna() 메서드를 이용해 이런 작업을 간단하게 처리할 수 있습니다.

In [17]:
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(housing, housing["income_cat"]):
    start_train_set = housing.loc[train_index]
    start_test_set=housing.loc[test_index]

In [18]:
housing = start_train_set.drop("median_house_value",axis=1)

In [19]:
housing_labels = start_train_set["median_house_value"].copy()

In [20]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
17606    -121.89     37.29                38.0       1568.0           351.0   
18632    -121.93     37.05                14.0        679.0           108.0   
14650    -117.20     32.77                31.0       1952.0           471.0   
3230     -119.61     36.31                25.0       1847.0           371.0   
3555     -118.59     34.23                17.0       6592.0          1525.0   
...          ...       ...                 ...          ...             ...   
6563     -118.13     34.20                46.0       1271.0           236.0   
12053    -117.56     33.88                40.0       1196.0           294.0   
13908    -116.40     34.09                 9.0       4855.0           872.0   
11159    -118.01     33.82                31.0       1960.0           380.0   
15775    -122.45     37.77                52.0       3095.0           682.0   

       population  households  median_income ocean_proximity income_cat  
17606       710.0       339.0         2.7042       <1H OCEAN          2  
18632       306.0       113.0         6.4214       <1H OCEAN          5  
14650       936.0       462.0         2.8621      NEAR OCEAN          2  
3230       1460.0       353.0         1.8839          INLAND          2  
3555       4459.0      1463.0         3.0347       <1H OCEAN          3  
...           ...         ...            ...             ...        ...  
6563        573.0       210.0         4.9312          INLAND          4  
12053      1052.0       258.0         2.0682          INLAND          2  
13908      2098.0       765.0         3.2723          INLAND          3  
11159      1356.0       356.0         4.0625       <1H OCEAN          3  
15775      1269.0       639.0         3.5750        NEAR BAY          3  

[16512 rows x 10 columns]

In [21]:
housing.dropna(subset=["total_bedrooms"])

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
17606    -121.89     37.29                38.0       1568.0           351.0   
18632    -121.93     37.05                14.0        679.0           108.0   
14650    -117.20     32.77                31.0       1952.0           471.0   
3230     -119.61     36.31                25.0       1847.0           371.0   
3555     -118.59     34.23                17.0       6592.0          1525.0   
...          ...       ...                 ...          ...             ...   
6563     -118.13     34.20                46.0       1271.0           236.0   
12053    -117.56     33.88                40.0       1196.0           294.0   
13908    -116.40     34.09                 9.0       4855.0           872.0   
11159    -118.01     33.82                31.0       1960.0           380.0   
15775    -122.45     37.77                52.0       3095.0           682.0   

       population  households  median_income ocean_proximity income_cat  
17606       710.0       339.0         2.7042       <1H OCEAN          2  
18632       306.0       113.0         6.4214       <1H OCEAN          5  
14650       936.0       462.0         2.8621      NEAR OCEAN          2  
3230       1460.0       353.0         1.8839          INLAND          2  
3555       4459.0      1463.0         3.0347       <1H OCEAN          3  
...           ...         ...            ...             ...        ...  
6563        573.0       210.0         4.9312          INLAND          4  
12053      1052.0       258.0         2.0682          INLAND          2  
13908      2098.0       765.0         3.2723          INLAND          3  
11159      1356.0       356.0         4.0625       <1H OCEAN          3  
15775      1269.0       639.0         3.5750        NEAR BAY          3  

[16354 rows x 10 columns]

In [22]:
housing.drop("total_bedrooms",axis=1)

longitude  latitude  housing_median_age  total_rooms  population  \
17606    -121.89     37.29                38.0       1568.0       710.0   
18632    -121.93     37.05                14.0        679.0       306.0   
14650    -117.20     32.77                31.0       1952.0       936.0   
3230     -119.61     36.31                25.0       1847.0      1460.0   
3555     -118.59     34.23                17.0       6592.0      4459.0   
...          ...       ...                 ...          ...         ...   
6563     -118.13     34.20                46.0       1271.0       573.0   
12053    -117.56     33.88                40.0       1196.0      1052.0   
13908    -116.40     34.09                 9.0       4855.0      2098.0   
11159    -118.01     33.82                31.0       1960.0      1356.0   
15775    -122.45     37.77                52.0       3095.0      1269.0   

       households  median_income ocean_proximity income_cat  
17606       339.0         2.7042       <1H OCEAN          2  
18632       113.0         6.4214       <1H OCEAN          5  
14650       462.0         2.8621      NEAR OCEAN          2  
3230        353.0         1.8839          INLAND          2  
3555       1463.0         3.0347       <1H OCEAN          3  
...           ...            ...             ...        ...  
6563        210.0         4.9312          INLAND          4  
12053       258.0         2.0682          INLAND          2  
13908       765.0         3.2723          INLAND          3  
11159       356.0         4.0625       <1H OCEAN          3  
15775       639.0         3.5750        NEAR BAY          3  

[16512 rows x 9 columns]

In [23]:
median = housing["total_bedrooms"].median()

In [24]:
median

433.0

In [25]:
housing["total_bedrooms"].fillna(median,inplace=True)

In [26]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
17606    -121.89     37.29                38.0       1568.0           351.0   
18632    -121.93     37.05                14.0        679.0           108.0   
14650    -117.20     32.77                31.0       1952.0           471.0   
3230     -119.61     36.31                25.0       1847.0           371.0   
3555     -118.59     34.23                17.0       6592.0          1525.0   
...          ...       ...                 ...          ...             ...   
6563     -118.13     34.20                46.0       1271.0           236.0   
12053    -117.56     33.88                40.0       1196.0           294.0   
13908    -116.40     34.09                 9.0       4855.0           872.0   
11159    -118.01     33.82                31.0       1960.0           380.0   
15775    -122.45     37.77                52.0       3095.0           682.0   

       population  households  median_income ocean_proximity income_cat  
17606       710.0       339.0         2.7042       <1H OCEAN          2  
18632       306.0       113.0         6.4214       <1H OCEAN          5  
14650       936.0       462.0         2.8621      NEAR OCEAN          2  
3230       1460.0       353.0         1.8839          INLAND          2  
3555       4459.0      1463.0         3.0347       <1H OCEAN          3  
...           ...         ...            ...             ...        ...  
6563        573.0       210.0         4.9312          INLAND          4  
12053      1052.0       258.0         2.0682          INLAND          2  
13908      2098.0       765.0         3.2723          INLAND          3  
11159      1356.0       356.0         4.0625       <1H OCEAN          3  
15775      1269.0       639.0         3.5750        NEAR BAY          3  

[16512 rows x 10 columns]

In [27]:
from sklearn.impute import SimpleImputer

In [28]:
imputer = SimpleImputer(strategy="median")

In [29]:
imputer

SimpleImputer(strategy='median')

In [30]:
housing_num = housing.drop("ocean_proximity",axis=1)

In [31]:
housing_num

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
17606    -121.89     37.29                38.0       1568.0           351.0   
18632    -121.93     37.05                14.0        679.0           108.0   
14650    -117.20     32.77                31.0       1952.0           471.0   
3230     -119.61     36.31                25.0       1847.0           371.0   
3555     -118.59     34.23                17.0       6592.0          1525.0   
...          ...       ...                 ...          ...             ...   
6563     -118.13     34.20                46.0       1271.0           236.0   
12053    -117.56     33.88                40.0       1196.0           294.0   
13908    -116.40     34.09                 9.0       4855.0           872.0   
11159    -118.01     33.82                31.0       1960.0           380.0   
15775    -122.45     37.77                52.0       3095.0           682.0   

       population  households  median_income income_cat  
17606       710.0       339.0         2.7042          2  
18632       306.0       113.0         6.4214          5  
14650       936.0       462.0         2.8621          2  
3230       1460.0       353.0         1.8839          2  
3555       4459.0      1463.0         3.0347          3  
...           ...         ...            ...        ...  
6563        573.0       210.0         4.9312          4  
12053      1052.0       258.0         2.0682          2  
13908      2098.0       765.0         3.2723          3  
11159      1356.0       356.0         4.0625          3  
15775      1269.0       639.0         3.5750          3  

[16512 rows x 9 columns]

In [32]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [33]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409,    3.    ])

In [34]:
housing_num.median().values

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409])

In [35]:
X = imputer.transform(housing_num)

In [36]:
housing_tr=pd.DataFrame(X,columns=housing_num.columns,index=housing_num.index)

In [37]:
housing_tr

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
17606    -121.89     37.29                38.0       1568.0           351.0   
18632    -121.93     37.05                14.0        679.0           108.0   
14650    -117.20     32.77                31.0       1952.0           471.0   
3230     -119.61     36.31                25.0       1847.0           371.0   
3555     -118.59     34.23                17.0       6592.0          1525.0   
...          ...       ...                 ...          ...             ...   
6563     -118.13     34.20                46.0       1271.0           236.0   
12053    -117.56     33.88                40.0       1196.0           294.0   
13908    -116.40     34.09                 9.0       4855.0           872.0   
11159    -118.01     33.82                31.0       1960.0           380.0   
15775    -122.45     37.77                52.0       3095.0           682.0   

       population  households  median_income  income_cat  
17606       710.0       339.0         2.7042         2.0  
18632       306.0       113.0         6.4214         5.0  
14650       936.0       462.0         2.8621         2.0  
3230       1460.0       353.0         1.8839         2.0  
3555       4459.0      1463.0         3.0347         3.0  
...           ...         ...            ...         ...  
6563        573.0       210.0         4.9312         4.0  
12053      1052.0       258.0         2.0682         2.0  
13908      2098.0       765.0         3.2723         3.0  
11159      1356.0       356.0         4.0625         3.0  
15775      1269.0       639.0         3.5750         3.0  

[16512 rows x 9 columns]

## 2.5.2 텍스트와 범주형 특성 다루기 

In [38]:
housing_cat=housing[["ocean_proximity"]]

In [39]:
housing_cat.head(10)

ocean_proximity
17606       <1H OCEAN
18632       <1H OCEAN
14650      NEAR OCEAN
3230           INLAND
3555        <1H OCEAN
19480          INLAND
8879        <1H OCEAN
13685          INLAND
4937        <1H OCEAN
4861        <1H OCEAN

In [40]:
from sklearn.preprocessing import OrdinalEncoder

In [41]:
ordinal_encoder = OrdinalEncoder()

In [42]:
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)

In [43]:
housing_cat_encoded[:10]

array([[0.],
       [0.],
       [4.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [44]:
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [45]:
from sklearn.preprocessing import OneHotEncoder

In [46]:
cat_encoder = OneHotEncoder()

In [47]:
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)

In [48]:
housing_cat_1hot

<16512x5 sparse matrix of type '<class 'numpy.float64'>'
	with 16512 stored elements in Compressed Sparse Row format>

In [49]:
housing_cat_1hot.toarray()

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [50]:
cat_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

## 2.5.3 나만의 변환기 

조합 특성을 추가하는 간단한 변환기 

변환기가 add_bedrooms_per_room 하이퍼파라미터 하나를 가지며 기본값을 True로 지정합니다. 합리적인 기본값을 주는 것이 좋습니다. 
데이터 준비 단계를 자동화할수록 더 많은 조합을 자동으로 시도해볼 수 있고 최상의 조합을 찾을 가능성을 매우 높여줍니다. 그리고 시간도 많이 절약됩니다.

In [66]:
from sklearn.base import BaseEstimator, TransformerMixin

rooms_ix, bedrooms_ix, population_ix, households_ix = 3,4,5,6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self,add_bedrooms_per_room=True): #*args나 **kargs가 아닙니다. 
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self,X,y=None) : 
        return self #더 할 일이 없습니다.
    def transform(self,X):
        rooms_per_household = X[:,rooms_ix] / X[:, households_ix]
        population_per_household = X[:,population_ix] / X[:,households_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:,bedrooms_ix] / X[:,rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]
attr_adder = CombinedAttributeAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing.values)

In [67]:
housing_extra_attribs

array([[-121.89, 37.29, 38.0, ..., 2, 4.625368731563422,
        2.094395280235988],
       [-121.93, 37.05, 14.0, ..., 5, 6.008849557522124,
        2.7079646017699117],
       [-117.2, 32.77, 31.0, ..., 2, 4.225108225108225,
        2.0259740259740258],
       ...,
       [-116.4, 34.09, 9.0, ..., 3, 6.34640522875817, 2.742483660130719],
       [-118.01, 33.82, 31.0, ..., 3, 5.50561797752809,
        3.808988764044944],
       [-122.45, 37.77, 52.0, ..., 3, 4.843505477308295,
        1.9859154929577465]], dtype=object)

## 2.5.4 특성 스케일링(feature scaling) 

모든 특성의 범위를 같도록 만들어주는 방법으로 min-max 스케일링과 표준화(standardization)가 널리 사용됩니다.

min-max 스케일링이 가장 간단합니다. 많은 사람들이 이를 정규화(normalization)라고 부릅니다. 0~1 범위에 들도록 값을 이동하고 스케일을 조정하면 됩니다. 데이터에서 최솟값을 뺀 후 최댓값과 최솟값의 차이로 나누면 이렇게 할 수 있습니다. 

표준화는 먼져 평균을 뺀 후(그래서 표준화를 하면 항상 평균이 0이 됩니다) 표준편차로 나누어 결과 분포의 분산이 1이 되도록 합니다. 표준화는 범위의 상한과 하한이 없어 어떤 알고리즘에서는 문제가 될 수 있습니다.(예를 들어 신경망은 종종 입력값의 범위로 0에서 1사이를 기대합니다.)그러나 표준화는 이상치에 영향을 덜 받습니다. 

**주의 : 모든 변환기에서 스케일링은 (테스트세트가 포함된) 전체 데이터가 아니고 훈련 데이터에 대해서만 fit() 메서드를 적용해야 합니다. 그런 다음 훈련 세트와 테스트 세트(그리고 새로운 데이터)에 대해 transform() 메서드를 사용합니다. 

## 2.5.5 변환 파이프라인

In [62]:
from sklearn.pipeline import Pipeline

In [64]:
from sklearn.preprocessing import StandardScaler

In [70]:
num_pipeline=Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    ('attribs_adder',CombinedAttributesAdder()),
    ('std_scaler',StandardScaler())
])

In [71]:
housing_num_tr = num_pipeline.fit_transform(housing_num)

In [72]:
housing_num_tr

array([[-1.15604281,  0.77194962,  0.74333089, ..., -0.31205452,
        -0.08649871,  0.15531753],
       [-1.17602483,  0.6596948 , -1.1653172 , ...,  0.21768338,
        -0.03353391, -0.83628902],
       [ 1.18684903, -1.34218285,  0.18664186, ..., -0.46531516,
        -0.09240499,  0.4222004 ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.3469342 ,
        -0.03055414, -0.52177644],
       [ 0.78221312, -0.85106801,  0.18664186, ...,  0.02499488,
         0.06150916, -0.30340741],
       [-1.43579109,  0.99645926,  1.85670895, ..., -0.22852947,
        -0.09586294,  0.10180567]])